# Using java 8
language: java

jdk:
- oraclejdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

# We dont need the whole history
git:
  depth: 3

# cache the build tool's caches
cache:
  directories:
   - $HOME/.m2
   - $HOME/.gradle

# We need to install manually gradle 5.3 to use the spring plugins
before_install:
  - cd rest-api 
  - wget http://services.gradle.org/distributions/gradle-5.3-bin.zip
  - unzip -qq gradle-5.3-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.3
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

# Jacoco report
after_success:
  - bash <(curl -s https://codecov.io/bash)
