language: java

# use Java 8
jdk:
- oraclejdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

git:
  depth: 3

before_install:
  - cd rest-api && gradle wrapper --gradle-version 5.4.1

# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
