export const FETCH_PORTFOLIOS_REQUEST = '@@portfolios/FETCH_PORTFOLIOS_REQUEST'
export const FETCH_PORTFOLIOS_SUCCESS = '@@portfolios/FETCH_PORTFOLIOS_SUCCESS'
export const FETCH_PORTFOLIOS_FAILURE = '@@portfolios/FETCH_PORTFOLIOS_FAILURE'

export const FETCH_PORTFOLIO_REQUEST = '@@portfolios/FETCH_PORTFOLIO_REQUEST'
export const FETCH_PORTFOLIO_SUCCESS = '@@portfolios/FETCH_PORTFOLIO_SUCCESS'
export const FETCH_PORTFOLIO_FAILURE = '@@portfolios/FETCH_PORTFOLIO_FAILURE'

export const FETCH_STOCKS_REQUEST = '@@stocks/FETCH_STOCKS_REQUEST'
export const FETCH_STOCKS_SUCCESS = '@@stocks/FETCH_STOCKS_SUCCESS'
export const FETCH_STOCKS_FAILURE = '@@stocks/FETCH_STOCKS_FAILURE'

export const FETCH_STOCK_REQUEST = '@@stocks/FETCH_STOCK_REQUEST'
export const FETCH_STOCK_SUCCESS = '@@stocks/FETCH_STOCK_SUCCESS'
export const FETCH_STOCK_FAILURE = '@@stocks/FETCH_STOCK_FAILURE'

export const FETCH_COUNTRIES_REQUEST = '@@countries/FETCH_COUNTRIES_REQUEST'
export const FETCH_COUNTRIES_SUCCESS = '@@countries/FETCH_COUNTRIES_SUCCESS'
export const FETCH_COUNTRIES_FAILURE = '@@countries/FETCH_COUNTRIES_FAILURE'

export const FETCH_COUNTRY_REQUEST = '@@countries/FETCH_COUNTRY_REQUEST'
export const FETCH_COUNTRY_SUCCESS = '@@countries/FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_FAILURE = '@@countries/FETCH_COUNTRY_FAILURE'

export const FETCH_SECTORS_REQUEST = '@@sectors/FETCH_SECTORS_REQUEST'
export const FETCH_SECTORS_SUCCESS = '@@sectors/FETCH_SECTORS_SUCCESS'
export const FETCH_SECTORS_FAILURE = '@@sectors/FETCH_SECTORS_FAILURE'

export const FETCH_SECTOR_REQUEST = '@@sectors/FETCH_SECTOR_REQUEST'
export const FETCH_SECTOR_SUCCESS = '@@sectors/FETCH_SECTOR_SUCCESS'
export const FETCH_SECTOR_FAILURE = '@@sectors/FETCH_SECTOR_FAILURE'

export const FETCH_CURRENCIES_REQUEST = '@@currencies/FETCH_CURRENCIES_REQUEST'
export const FETCH_CURRENCIES_SUCCESS = '@@currencies/FETCH_CURRENCIES_SUCCESS'
export const FETCH_CURRENCIES_FAILURE = '@@currencies/FETCH_CURRENCIES_FAILURE'

export const FETCH_CURRENCY_REQUEST = '@@currencies/FETCH_CURRENCY_REQUEST'
export const FETCH_CURRENCY_SUCCESS = '@@currencies/FETCH_CURRENCY_SUCCESS'
export const FETCH_CURRENCY_FAILURE = '@@currencies/FETCH_CURRENCY_FAILURE'